# Generated by Django 5.0.6 on 2024-05-22 07:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="experiences",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="skill",
            name="imageSrc",
            field=models.ImageField(blank=True, null=True, upload_to="project_images"),
        ),
        migrations.AlterField(
            model_name="socialmedia",
            name="contact_no",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="socialmedia",
            name="facebook_link",
            field=models.URLField(blank=True, default="#", null=True),
        ),
        migrations.AlterField(
            model_name="socialmedia",
            name="github_link",
            field=models.URLField(blank=True, default="#", null=True),
        ),
        migrations.AlterField(
            model_name="socialmedia",
            name="instagram_link",
            field=models.URLField(blank=True, default="#", null=True),
        ),
        migrations.AlterField(
            model_name="socialmedia",
            name="linkedin_link",
            field=models.URLField(blank=True, default="#", null=True),
        ),
        migrations.AlterField(
            model_name="socialmedia",
            name="mail",
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="socialmedia",
            name="twitter_link",
            field=models.URLField(blank=True, default="#", null=True),
        ),
    ]
