# Generated by Django 5.0.6 on 2024-05-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_certificate_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialmedia",
            name="facebook_link",
            field=models.URLField(
                blank=True, default="https://www.example.com", null=True
            ),
        ),
        migrations.AlterField(
            model_name="socialmedia",
            name="github_link",
            field=models.URLField(
                blank=True, default="https://www.example.com", null=True
            ),
        ),
        migrations.AlterField(
            model_name="socialmedia",
            name="instagram_link",
            field=models.URLField(
                blank=True, default="https://www.example.com", null=True
            ),
        ),
        migrations.AlterField(
            model_name="socialmedia",
            name="linkedin_link",
            field=models.URLField(
                blank=True, default="https://www.example.com", null=True
            ),
        ),
        migrations.AlterField(
            model_name="socialmedia",
            name="twitter_link",
            field=models.URLField(
                blank=True, default="https://www.example.com", null=True
            ),
        ),
    ]
